app: graphql-plus-plus
config:
  userAgent:
    fromSecret: userAgent
  userToken:
    fromSecret: userToken
files:
  - build/index.html
  - build/static/js/main.b9317702.js
  - build/static/css/main.daa945be.css