platform: x64
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
install:
 - git submodule update --init --recursive --quiet
 - ps: Install-Product node $env:nodejs_version x64
 - yarn install
test_script:
 - yarn build
 - yarn test
build: off