platform: x64
environment:
  matrix:
    - nodejs_version: "8"
    - nodejs_version: "10"
install:
 - ps: Install-Product node $env:nodejs_version x64
 - yarn install
test_script:
  - node --version
  - yarn test
build: off