# Node.js
# Build a general Node.js application with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/javascript

jobs:
- job: macOS
  pool: 
    vmImage: xcode9-macos10.13
  strategy:
    matrix:
      node-8:
        node_version: 8
      node-10-3:
        node_version: 10.3
      node-10.9:
        node_version: 10.9
  variables:
    CI: true
  timeoutInMinutes: 10
  steps:
  - task: NodeTool@0
    inputs: 
      versionSpec: $(node_version)
      checkLatest: $(node_check_latest)
  - script: npm install -g yarn
  - script: yarn install --no-progress
  - script: yarn bootstrap --no-progress
  - script: yarn build
  - script: yarn bundle
  - script: yarn test
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: '**/*junit.xml' 
      searchFolder: $(Build.SourcesDirectory)/artifacts

- job: Linux
  pool: 
    vmImage: ubuntu-16.04
  strategy:
    matrix:
      node-8:
        node_version: 8
      node-10-3:
        node_version: 10.3
      node-10.9:
        node_version: 10.9
  variables:
    CI: true
  timeoutInMinutes: 10
  steps:
  - task: NodeTool@0
    inputs: 
      versionSpec: $(node_version)
      checkLatest: $(node_check_latest)
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '2.7'
      architecture: 'x64'
  - script: apt-get update && apt-get install -y nasm
  - script: npm install -g yarn
  - script: yarn install --no-progress
  - script: yarn bootstrap --no-progress
  - script: yarn build
  - script: yarn bundle
  - script: yarn test
  - task: PublishTestResults@2
    condition: always()
    inputs:
      testResultsFiles: '**/*junit.xml' 
      searchFolder: $(Build.SourcesDirectory)/artifacts

# - job: Windows
#   pool: 
#     vmImage: vs2017-win2016
#   timeoutInMinutes: 10
#   steps:
#   - task: NodeTool@0
#     inputs: 
#       versionSpec: 10.8
#   - task: UsePythonVersion@0
#     inputs:
#       versionSpec: '2.7'
#       architecture: 'x64'
#   # for node-gyp
#   - script: npm install --global --production windows-build-tools
#   - script: npm install -g yarn
#   - script: yarn install --no-progress --verbose
#   - script: yarn bootstrap --no-progress
#   - script: yarn build
#   - script: yarn bundle
#   - script: yarn test
