#!/bin/bash

set -e

# trigger action in superfly/homebrew-brew

curl \
  -XPOST -u "$GITHUB_AUTH" \
  -H "Accept: application/vnd.github.everest-preview+json" \
  -H "Content-Type: application/json" \
  https://api.github.com/repos/superfly/homebrew-brew/dispatches \
  --data '{"event_type": "release"}'
