#!/bin/sh

VERSION=$(node -p "require('./lerna.json').version")
CHANNEL=$(echo $VERSION | awk -F'[.-]' '{print $4}')
CHANNEL="${CHANNEL:-stable}"

echo "$VERSION $CHANNEL"

if [[ $CHANNEL == "stable" ]]; then
  echo "release stable"
  lerna publish from-package -y
else
  echo "release $CHANNEL"
  lerna publish from-package --npm-tag "$CHANNEL" -y
fi
