#!/bin/bash

set -e

VERSION=$(node -p "require('./lerna.json').version")
CHANNEL=$(echo $VERSION | awk -F'[.-]' '{print $4}')
CHANNEL="${CHANNEL:-stable}"

echo "$VERSION $CHANNEL"

git status
git diff

if [[ $CHANNEL == "stable" ]]; then
  echo "release stable"
  yarn lerna publish from-package -y
else
  echo "release $CHANNEL"
  yarn lerna publish from-package --dist-tag "$CHANNEL" -y
fi
