#!/bin/bash

set -ex

TARGET=$1

echo "Packing CLI for $TARGET"

cp ./yarn.lock ./packages/cli
cd ./packages/cli

./node_modules/.bin/oclif-dev pack -t $TARGET

find . -name "*-$TARGET.tar.gz" -exec mv {} './artifacts/dist/' \;
