#!/bin/bash

set -ex

TARGET=$1

echo "Linking workspace packages"
# lerna exec --no-private yarn link

echo "Packing CLI for $TARGET"

cp ./yarn.lock ./packages/cli
cd ./packages/cli

LDFLAGS=""
if [ "\$(expr substr \$(uname -s) 1 5)" == "Linux" ]; then
  # statically link libstdc++ & libgcc on linux
  LDFLAGS='-static-libgcc -static-libstdc++'
fi

LDFLAGS=$LDFLAGS yarn oclif-dev pack -t $TARGET

echo "ldd"
# ldd
