#!/bin/bash

docker build . -f docker/base.Dockerfile -t fly-js-app-base
docker build . --build-arg BASE_IMAGE=fly-js-app-base -f docker/build.Dockerfile -t flyio/js-app-build
docker build . --build-arg BASE_IMAGE=fly-js-app-base -f docker/run.Dockerfile -t flyio/js-app-run
